name: Build iOS App
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Change Bundle Identifier
        run: |
          find . -name "project.pbxproj" -exec sed -i '' 's/org.meshtastic.Meshtastic/org.brzknvmeshname.meshtastic/g' {} +
      - name: Build IPA
        run: |
          xcodebuild -workspace Meshtastic.xcworkspace \
                     -scheme Meshtastic \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGNING_ALLOWED=NO \
                     archive -archivePath ./build/Meshtastic.xcarchive
